spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzw?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
---
server:
  port: 8082

---
mybatis:
  type-aliases-package: com.wzw.drugstore.entity

---
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
