#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wzw?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#
#---
#mybatis:
#  mapper-locations: com.wzw.mapper/*.xml
#  type-aliases-package: com.wzw.entity
#
#---
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
